This is a testharness.js-based test.
[FAIL] A clone should be used in an isolated world, but only one clone
  promise_test: Unhandled rejection with value: object "ReferenceError: testRunner is not defined"
Harness: the test ran to completion.
