This is a testharness.js-based test.
[FAIL] open() rejects in a detached context
  promise_test: Unhandled rejection with value: object "ReferenceError: GCController is not defined"
[FAIL] forget() rejects in a detached context
  promise_test: Unhandled rejection with value: object "ReferenceError: GCController is not defined"
Harness: the test ran to completion.
